"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
type CategoryRow = { id: string; name: string; slug: string; productCount: number };
const slugify = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
export default function CategoryManager({ initialCategories }: { initialCategories: CategoryRow[] }) {
  const router = useRouter(); const [editing,setEditing] = useState<CategoryRow|null>(null); const [message,setMessage] = useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setMessage("");const form=new FormData(event.currentTarget);const name=String(form.get("name"));const response=await fetch(editing?`/api/admin/categories/${editing.id}`:"/api/admin/categories",{method:editing?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,slug:slugify(String(form.get("slug")||name))})});const result=await response.json();if(!response.ok)return setMessage(result.error??"Não foi possível salvar.");setMessage("Categoria salva com sucesso.");setEditing(null);(event.currentTarget as HTMLFormElement).reset();router.refresh();}
  return <><header className="admin-heading"><div><small>CATÁLOGO</small><h1>Categorias</h1><p>Organize os produtos exibidos na loja.</p></div></header><div className="category-layout"><form className="admin-form compact" onSubmit={submit}><h2>{editing?"Editar categoria":"Nova categoria"}</h2><label>Nome<input name="name" defaultValue={editing?.name} key={`name-${editing?.id}`} required /></label><label>Slug<input name="slug" defaultValue={editing?.slug} key={`slug-${editing?.id}`} placeholder="gerado a partir do nome" /></label>{message&&<p className="form-message">{message}</p>}<div className="form-actions">{editing&&<button type="button" onClick={()=>setEditing(null)}>Cancelar</button>}<button className="admin-primary">Salvar</button></div></form><section className="category-list">{initialCategories.map((item)=><article key={item.id}><div><b>{item.name}</b><small>{item.slug} · {item.productCount} {item.productCount===1?"produto":"produtos"}</small></div><button onClick={()=>setEditing(item)}>Editar</button></article>)}</section></div></>;
}
