import { OrderStatus, Prisma, ProductStatus, ProductType } from "@prisma/client";
import { prisma } from "./prisma";

export type PublicCatalogFilters={query?:string;category?:string;brand?:string;type?:ProductType;sort?:"priority"|"recent"|"name"};
export const normalizeSearch=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("pt-BR").trim();
export const searchTokens=(value:string)=>normalizeSearch(value).split(/\s+/).filter(Boolean);
export function matchesSearch(product:{name:string;slug:string;description:string;searchTerms:string;type:string;category:{name:string;slug:string};brand:{name:string;slug:string}|null},query:string){const haystack=normalizeSearch([product.name,product.slug,product.description,product.searchTerms,product.type,product.category.name,product.category.slug,product.brand?.name,product.brand?.slug].filter(Boolean).join(" "));return searchTokens(query).every(token=>haystack.includes(token))}
export function stableCatalogSort<T extends {featured:boolean;sortOrder:number;name:string}>(products:T[]){return [...products].sort((a,b)=>Number(b.featured)-Number(a.featured)||b.sortOrder-a.sortOrder||a.name.localeCompare(b.name,"pt-BR"))}
export const completedSaleStatuses:OrderStatus[]=[OrderStatus.PAID,OrderStatus.PROCESSING,OrderStatus.FULFILLED,OrderStatus.DELIVERED];
const include={category:true,brand:true,providerProducts:{where:{active:true,mode:"REAL" as const},include:{provider:true}}} as const;
function whereFor(filters:PublicCatalogFilters):Prisma.ProductWhereInput{return{status:ProductStatus.PUBLISHED,available:true,category:{active:true},...(filters.category?{category:{slug:filters.category,active:true}}:{}),...(filters.brand?{brand:{slug:filters.brand,active:true}}:{}),...(filters.type?{type:filters.type}:{})}}
export async function findPublicCatalog(filters:PublicCatalogFilters={}){const products=await prisma.product.findMany({where:whereFor(filters),include,take:120,orderBy:filters.sort==="recent"?[{createdAt:"desc"},{id:"asc"}]:filters.sort==="name"?[{name:"asc"},{id:"asc"}]:[{featured:"desc"},{sortOrder:"desc"},{name:"asc"},{id:"asc"}]});return filters.query?stableCatalogSort(products.filter(product=>matchesSearch(product,filters.query!))):products}
export async function recentPublicProducts(limit=5){return prisma.product.findMany({where:whereFor({}),include,take:limit,orderBy:[{createdAt:"desc"},{id:"asc"}]})}
export async function featuredPublicProducts(limit=5){return prisma.product.findMany({where:{...whereFor({}),featured:true},include,take:limit,orderBy:[{sortOrder:"desc"},{name:"asc"}]})}
export async function withEditorialFallback<T>(primary:()=>Promise<T[]|null>,editorial:()=>Promise<T[]>,log:(message:string,error:unknown)=>void=console.error){try{const products=await primary();if(products)return{source:"sales" as const,products}}catch(error){log("[catalog] Falha na consulta auxiliar de produtos mais procurados.",error)}try{const products=await editorial();return{source:products.length?"featured" as const:"empty" as const,products}}catch(fallbackError){log("[catalog] Falha no fallback editorial de produtos.",fallbackError);return{source:"empty" as const,products:[] as T[]}}}
export async function popularPublicProducts(limit=5){return withEditorialFallback(async()=>{const sales=await prisma.orderItem.groupBy({by:["productId"],where:{order:{status:{in:completedSaleStatuses}},product:{status:ProductStatus.PUBLISHED,available:true}},_count:{productId:true},orderBy:{_count:{productId:"desc"}},take:limit});if(!sales.length)return null;const products=await prisma.product.findMany({where:{id:{in:sales.map(x=>x.productId)},...whereFor({})},include});const rank=new Map(sales.map((x,index)=>[x.productId,index]));return products.sort((a,b)=>(rank.get(a.id)??999)-(rank.get(b.id)??999))},()=>featuredPublicProducts(limit))}
export async function optionalHomeQuery<T>(label:string,query:()=>Promise<T>,fallback:T,log:(message:string,error:unknown)=>void=console.error){try{return await query()}catch(error){log(`[home] Falha na consulta auxiliar: ${label}.`,error);return fallback}}
