import { describe, expect, it, vi } from "vitest";
import { isAdminRole } from "../authorization";
import { ASAAS_SANDBOX_URL, publicAsaasDiagnostic, readAsaasRuntimeConfig, testAsaasConnection } from "./asaas-diagnostics";
import { handleAdminAsaasConnectionTest } from "./asaas-admin-route";

const validEnv: NodeJS.ProcessEnv = { NODE_ENV:"test", PAYMENT_PROVIDER:"asaas", ASAAS_ENV:"sandbox", ASAAS_BASE_URL:ASAAS_SANDBOX_URL, ASAAS_API_KEY:"test-only-key", ASAAS_WEBHOOK_TOKEN:"test-only-webhook" };

describe("Asaas admin diagnostic", () => {
  it("recognizes ADMIN and blocks USER through the shared authorization rule", () => { expect(isAdminRole("ADMIN")).toBe(true); expect(isAdminRole("USER")).toBe(false); });
  it("reports Asaas and Mock selections", () => { expect(readAsaasRuntimeConfig(validEnv).provider).toBe("asaas"); expect(readAsaasRuntimeConfig({ ...validEnv, PAYMENT_PROVIDER:"mock" }).provider).toBe("mock"); });
  it.each([undefined, "", "   "])("rejects a missing or blank API key", (key) => expect(readAsaasRuntimeConfig({ ...validEnv, ASAAS_API_KEY:key }).configurationError).toBe(true));
  it("rejects control characters inside the API key before fetch", async () => { const fetcher=vi.fn();const result=await testAsaasConnection({...validEnv,ASAAS_API_KEY:"test\nkey"},fetcher);expect(result).toMatchObject({apiKeyConfigured:true,apiKeyHeaderValid:false,reason:"API_KEY_HEADER_INVALID",category:"HEADER",requestAttempted:false});expect(fetcher).not.toHaveBeenCalled(); });
  it("rejects a base URL outside the allowlist", () => expect(readAsaasRuntimeConfig({ ...validEnv, ASAAS_BASE_URL:"https://example.test/v3" })).toMatchObject({ baseUrl:"INVALID", baseUrlStatus:"INVALID", configurationError:true }));
  it("reports authenticated HTTP 200 without returning the response body", async () => { const result=await testAsaasConnection(validEnv,vi.fn(async()=>new Response(JSON.stringify({balance:999}),{status:200})));expect(result).toMatchObject({ok:true,authentication:"ONLINE",httpStatus:200});expect(result).not.toHaveProperty("balance");expect(result).not.toHaveProperty("body");expect(JSON.stringify(result)).not.toContain("999"); });
  it("reports HTTP 401 safely", async () => expect(testAsaasConnection(validEnv,vi.fn(async()=>new Response(null,{status:401})))).resolves.toMatchObject({ok:false,authentication:"ERROR",httpStatus:401}));
  it("normalizes invisible whitespace in the Production API key before constructing the header", async () => { const fetcher=vi.fn(async(input:string|URL|Request)=>{if(input instanceof Request)expect(input.headers.get("access_token")).toBe("test-only-key");return new Response(null,{status:200})});const result=await testAsaasConnection({...validEnv,ASAAS_API_KEY:"  test-only-key\r\n"},fetcher);expect(fetcher).toHaveBeenCalledTimes(2);expect(result).toMatchObject({ok:true,httpStatus:200,reason:null,requestUrlValid:true,apiKeyHeaderValid:true,connectivity:{reachable:true}}); });
  it("reports timeout/network failure without leaking configuration", async () => { const result=await testAsaasConnection(validEnv,vi.fn(async()=>{throw new DOMException("Aborted","AbortError")}));expect(result).toMatchObject({ok:false,authentication:"ERROR",httpStatus:null});expect(JSON.stringify(result)).not.toContain("test-only-key"); });
  it("captures a safe low-level DNS cause without exposing the original message", async () => { const failure=Object.assign(new TypeError("fetch failed and secret=test-only-key"),{cause:Object.assign(new Error("lookup failed"),{code:"ENOTFOUND"})});const result=await testAsaasConnection(validEnv,vi.fn(async()=>{throw failure}));expect(result).toMatchObject({requestAttempted:true,reason:"NETWORK_ERROR",target:{host:"api-sandbox.asaas.com",path:"/v3/finance/balance"},error:{name:"TypeError",causeCode:"ENOTFOUND",category:"DNS"}});expect(JSON.stringify(result)).not.toContain("test-only-key"); });
  it("identifies a pre-HTTP header rejection safely", async () => { const failure=Object.assign(new TypeError("invalid header value"),{code:"INVALID_HEADER_VALUE"});const result=await testAsaasConnection(validEnv,vi.fn(async()=>{throw failure}));expect(result).toMatchObject({httpStatus:null,requestAttempted:true,error:{category:"HEADER",code:"INVALID_HEADER_VALUE"}}); });
  it("captures non-enumerable cause metadata used by Node fetch safely", async () => { const cause=Object.assign(new Error("private detail"),{code:"ECONNRESET",errno:"-54",syscall:"read",hostname:"api-sandbox.asaas.com"});const failure=new TypeError("fetch failed",{cause});const result=await testAsaasConnection(validEnv,vi.fn(async()=>{throw failure}));expect(result.error).toMatchObject({constructorName:"TypeError",causeConstructorName:"Error",causeCode:"ECONNRESET",causeErrno:"-54",causeSyscall:"read",causeHostname:"api-sandbox.asaas.com",category:"SOCKET"});expect(JSON.stringify(result)).not.toContain("private detail"); });
  it("distinguishes host reachability from a finance endpoint failure", async () => { const fetcher=vi.fn().mockResolvedValueOnce(new Response(null,{status:404})).mockRejectedValueOnce(new TypeError("fetch failed"));const result=await testAsaasConnection(validEnv,fetcher);expect(result).toMatchObject({connectivity:{attempted:true,reachable:true,httpStatus:404},requestAttempted:true,httpStatus:null,error:{category:"NETWORK"}}); });
  it("safe configuration never exposes keys, tokens, or the effective URL", () => { const result=publicAsaasDiagnostic(readAsaasRuntimeConfig(validEnv));expect(result).not.toHaveProperty("apiKey");expect(result).not.toHaveProperty("effectiveBaseUrl");expect(JSON.stringify(result)).not.toContain("test-only"); });
  it("allows ADMIN to run the protected diagnostic", async () => { const response=await handleAdminAsaasConnectionTest(async()=>({role:"ADMIN"}),async()=>testAsaasConnection(validEnv,vi.fn(async()=>new Response(null,{status:200}))));expect(response.status).toBe(200);expect(await response.json()).toMatchObject({data:{authentication:"ONLINE"}}); });
  it("blocks USER before the diagnostic executes", async () => { const diagnose=vi.fn();const response=await handleAdminAsaasConnectionTest(async()=>{throw new Error("FORBIDDEN")},diagnose);expect(response.status).toBe(403);expect(diagnose).not.toHaveBeenCalled(); });
});
