import Link from "next/link";
import PublicHeader from "@/components/public-header";
import PublicFooter from "@/components/public-footer";
import ProductCard from "@/components/product-card";
import { prisma } from "@/lib/prisma";
import { popularPublicProducts, recentPublicProducts } from "@/lib/catalog-search";
import { productDto } from "@/lib/dto";

export const dynamic="force-dynamic";
export default async function Home(){
  const popular=await popularPublicProducts(5);const recentRaw=await recentPublicProducts(8);const popularIds=new Set(popular.products.map(p=>p.id));const recent=recentRaw.filter(p=>!popularIds.has(p.id)).slice(0,5);const categories=await prisma.category.findMany({where:{active:true,products:{some:{status:"PUBLISHED",available:true}}},select:{id:true,name:true,slug:true},orderBy:{name:"asc"}});
  return <main><PublicHeader/><section className="hero" id="inicio"><div className="wrap hero-grid"><div className="hero-copy"><span className="eyebrow">Plataforma para assistência técnica</span><h1>Encontrou.<br/>Pagou.<br/><em>Liberou.</em></h1><p>Ferramentas e serviços para o técnico, com compra simples e pagamento via PIX.</p><div className="hero-actions"><Link className="primary-cta" href="/catalogo">Ver catálogo</Link><Link className="secondary-cta" href="#como-funciona">Como funciona</Link></div><div className="trust-row"><span><b>↯</b>Fluxo<br/>automatizado</span><span><b>▣</b>Pagamento<br/>seguro</span><span><b>◉</b>Suporte<br/>em português</span></div></div><div className="hero-visual" aria-hidden="true"><div className="device-glow"/><div className="phone"><div className="phone-notch"/><div className="phone-message">Soluções para quem<br/>faz mais com técnica.</div><div className="phone-brand">BANCADA<span>SOFT</span></div></div></div><aside className="hero-list"><strong>Catálogo técnico</strong><small>soluções em um só lugar</small><ul><li>Aluguéis de ferramentas</li><li>Licenças e ativações</li><li>Serviços remotos</li><li>Créditos e consultas</li><li>Compra segura</li></ul></aside></div></section>
  <section className="wrap quick-links" aria-label="Categorias">{categories.map((item,index)=><Link key={item.id} href={`/catalogo?categoria=${item.slug}`}><span className="category-icon">{["⚙","↯","◆","◉","▰"][index%5]}</span><span><b>{item.name}</b><small>Explorar categoria</small></span></Link>)}</section>
  {popular.products.length>0&&<section className="wrap catalogue discovery-section"><div className="section-title"><div><h2><span>♦</span> {popular.source==="sales"?"Mais procurados":"Destaques"}</h2><p>{popular.source==="sales"?"Produtos mais comprados em pedidos confirmados.":"Seleção editorial do catálogo."}</p></div><Link href="/catalogo?ordem=populares">Ver catálogo →</Link></div><div className="products">{popular.products.map((p,i)=><ProductCard key={p.id} product={productDto(p)} index={i}/>)}</div></section>}
  {recent.length>0&&<section className="wrap catalogue discovery-section"><div className="section-title"><div><h2>Adicionados recentemente</h2><p>Novidades publicadas no catálogo.</p></div><Link href="/catalogo?ordem=recentes">Ver todos →</Link></div><div className="products">{recent.map((p,i)=><ProductCard key={p.id} product={productDto(p)} index={i}/>)}</div></section>}
  <section className="wrap pix-strip"><div className="pix-brand"><span>◆</span> pix</div><p>Pague com <b>PIX</b><br/>e acompanhe seu pedido.</p><div className="pix-points"><span>◷ Pagamento rápido</span><span>▣ Ambiente seguro</span><span>↯ Atualização automática</span></div></section><section className="wrap benefits"><article><span>✓</span><div><b>Catálogo atualizado</b><small>Soluções para a bancada.</small></div></article><article><span>♟</span><div><b>Suporte especializado</b><small>Atendimento em português.</small></div></article><article><span>▣</span><div><b>Compra sem burocracia</b><small>Fluxo simples e seguro.</small></div></article><article><span>★</span><div><b>Área do cliente</b><small>Acompanhe seus pedidos.</small></div></article></section><section className="wrap how" id="como-funciona"><h2>Como funciona?</h2><p>Em poucos passos você solicita sua ferramenta.</p><div className="steps"><article><span>1</span><div><b>Escolha o produto</b><small>Pesquise no catálogo.</small></div></article><article><span>2</span><div><b>Pague com PIX</b><small>Conclua em ambiente seguro.</small></div></article><article><span>3</span><div><b>Acompanhe</b><small>Veja o status do pedido.</small></div></article><article><span>4</span><div><b>Receba a entrega</b><small>Acesse quando disponível.</small></div></article></div></section><PublicFooter/></main>}
