import{NextResponse}from"next/server";import{requireAdmin}from"@/lib/auth";import{executeFulfillment,FulfillmentEngineError}from"@/lib/fulfillment-engine";import{audit}from"@/lib/audit";import{prisma}from"@/lib/prisma";type Context={params:Promise<{id:string}>};
export async function GET(_:Request,context:Context){try{await requireAdmin()}catch{return NextResponse.json({error:"Não autorizado."},{status:403})}const{id}=await context.params;const order=await prisma.order.findUnique({where:{id},select:{payment:{select:{status:true}},status:true,fulfillment:{select:{providerOrders:{select:{status:true,attempts:true,requestReference:true,externalOrderId:true,lastError:true,_count:{select:{callbackEvents:true}}}}}}}});const item=order?.fulfillment?.providerOrders[0];
// Sem ProviderOrder (fulfillment nunca chegou a chamar o provider — inclusive
// quando Fulfillment(FAILED) foi registrado sem ProviderOrder, ver
// recordPaidFulfillmentFailure em fulfillment-engine.ts), a primeira execução
// real é tão segura quanto um retry limpo: executeFulfillment decide sozinho
// o modo correto (ver POST abaixo).
const neverReachedProvider=!item;const failedClean=Boolean(item&&item.status==="FAILED"&&item.attempts<3&&!item.requestReference&&!item.externalOrderId&&!item.lastError&&item._count.callbackEvents===0);const baseOk=order?.payment?.status==="PAID"&&order?.status!=="DELIVERED";const allowed=Boolean(baseOk&&(failedClean||neverReachedProvider));return NextResponse.json({data:{allowed,reason:allowed?null:"RECONCILIATION_REQUIRED"}})}
export async function POST(_:Request,context:Context){let admin;try{admin=await requireAdmin()}catch{return NextResponse.json({error:"Não autorizado."},{status:403})}const{id}=await context.params;const order=await prisma.order.findUnique({where:{id},select:{fulfillment:{select:{providerOrders:{select:{id:true}}}}}});const retry=Boolean(order?.fulfillment?.providerOrders.length);try{const result=await executeFulfillment(id,{retry});await audit(admin.id,retry?"FULFILLMENT_RETRY":"FULFILLMENT_RECOVER","Order",id,{result:"accepted"});return NextResponse.json({data:result})}catch(error){const message=error instanceof FulfillmentEngineError?error.code:"Falha ao executar retry.";return NextResponse.json({error:message},{status:409})}}
